name: Build
on:
  push:
    branches:
      - master
      - frontend
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  #SONARCLOUD
  sonarcloud:
    name: DockerHub
    runs-on: ubuntu-latest
    steps:
      #DOCKER HUB
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/solcoin:latest .
  
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/solcoin:latest
